title: Hotdog training images
hero_image: images/banner.png
description: a collection of images of hotdogs to train a machine learning model
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - title: Hotdog training images